# Generated by Django 5.2.10 on 2026-02-01 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automatedjobmatch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='ats_feedback',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed ATS score breakdown'),
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='cover_letter_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error log if failed'),
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='hr_email',
            field=models.EmailField(blank=True, help_text='Recruiter/HR contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='Application submitted'),
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='platform_job_id',
            field=models.CharField(blank=True, help_text='Unique ID from job platform', max_length=255),
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='status',
            field=models.CharField(choices=[('found', 'Found'), ('tailoring', 'Tailoring CV'), ('ready', 'Ready to Apply'), ('applying', 'Applying'), ('applied', 'Applied'), ('email_sent', 'Email Notification Sent'), ('failed', 'Failed'), ('duplicate', 'Duplicate Skipped')], default='found', max_length=20),
        ),
        migrations.AddField(
            model_name='automatedjobmatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='auto_apply',
            field=models.BooleanField(default=False, help_text='Auto-apply to matching jobs'),
        ),
        migrations.AddField(
            model_name='job',
            name='headless_mode',
            field=models.BooleanField(default=True, help_text='Run browser in headless mode'),
        ),
        migrations.AlterField(
            model_name='automatedjobmatch',
            name='ats_score',
            field=models.IntegerField(default=0, help_text='ATS compatibility score (target: ≥90)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='automatedjobmatch',
            name='tailored_cv_text',
            field=models.TextField(help_text='ATS-optimized resume content'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='platform',
            field=models.CharField(help_text='LinkedIn, Indeed, Xing, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('searching', 'Searching'), ('applying', 'Applying'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='automatedjobmatch',
            unique_together={('job_query', 'platform_job_id')},
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('search', 'Searching Jobs'), ('scroll', 'Scrolling Page'), ('click', 'Clicking Element'), ('fill', 'Filling Form'), ('upload', 'Uploading File'), ('submit', 'Submitting Application'), ('captcha', 'CAPTCHA Detected'), ('error', 'Error Occurred'), ('success', 'Success')], max_length=20)),
                ('description', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='automation_screenshots/%Y/%m/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='applications.automatedjobmatch')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('platform', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('opened', 'Opened')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification', to='applications.automatedjobmatch')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tailored_resumes/%Y/%m/')),
                ('content_text', models.TextField()),
                ('ats_score', models.IntegerField(default=0)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_versions', to='applications.automatedjobmatch')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('base_cv_file', models.FileField(blank=True, null=True, upload_to='base_resumes/%Y/%m/')),
                ('base_cv_text', models.TextField(blank=True, help_text='Extracted text from base CV')),
                ('skills', models.JSONField(default=list, help_text='List of user skills')),
                ('preferred_job_titles', models.JSONField(default=list, help_text='Target job titles')),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('xing', 'Xing'), ('glassdoor', 'Glassdoor')], max_length=20)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_encrypted', models.BinaryField(blank=True, null=True)),
                ('search_url_template', models.CharField(blank=True, max_length=500)),
                ('daily_apply_limit', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
