# Generated by Django 5.2.10 on 2026-02-04 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_automatedjobmatch_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailnotification',
            name='error_log',
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='action',
            field=models.CharField(choices=[('info', 'Information'), ('action', 'Browser Action'), ('success', 'Success'), ('error', 'Error'), ('search', 'Searching'), ('fill', 'Filling'), ('submit', 'Submitting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='automatedjobmatch',
            name='ats_feedback',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='automatedjobmatch',
            name='ats_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='automatedjobmatch',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='automatedjobmatch',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='automatedjobmatch',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automatedjobmatch',
            name='platform_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='auto_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='headless_mode',
            field=models.BooleanField(default=False, help_text='Run browser in headless mode'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('xing', 'Xing')], max_length=20),
        ),
    ]
