# Generated by Django 5.2.10 on 2026-02-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_emailnotification_error_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlog',
            name='action',
            field=models.CharField(choices=[('info', 'System Info'), ('action', 'Browser Action'), ('success', 'Success'), ('error', 'Error'), ('search', 'Searching'), ('fill', 'Filling'), ('submit', 'Submitting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='auto_apply',
            field=models.BooleanField(default=False, help_text='Auto-apply to matching jobs'),
        ),
    ]
