# Generated by Django 5.2.10 on 2026-02-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_applicationlog_action_alter_job_auto_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformconfig',
            name='password_encrypted',
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='password',
            field=models.CharField(blank=True, help_text='Your login password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='search_url_template',
            field=models.CharField(blank=True, help_text='Optional: URL pattern for job searches', max_length=500),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='username',
            field=models.CharField(blank=True, help_text='Your login email/username', max_length=255),
        ),
    ]
