# Generated by Django 5.2.10 on 2026-02-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_platformconfig_password_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlog',
            name='action',
            field=models.CharField(choices=[('info', 'Information'), ('action', 'Browser Action'), ('success', 'Success Achievement'), ('error', 'Critical Error'), ('search', 'Searching'), ('fill', 'Filling'), ('submit', 'Submitting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='auto_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='headless_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='password',
            field=models.CharField(blank=True, help_text='Login password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='search_url_template',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='username',
            field=models.CharField(blank=True, help_text='Login email', max_length=255),
        ),
    ]
