# Generated by Django 5.2.10 on 2026-02-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_applicationlog_action_alter_job_auto_apply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlog',
            name='action',
            field=models.CharField(choices=[('info', 'System Info'), ('action', 'Browser Action'), ('success', 'Success'), ('error', 'Critical Error'), ('search', 'Searching'), ('fill', 'Filling Form'), ('submit', 'Submitting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='headless_mode',
            field=models.BooleanField(default=False, help_text='Run browser in headless mode'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='username',
            field=models.CharField(blank=True, help_text='Login email/username', max_length=255),
        ),
    ]
