# Generated by Django 5.2.10 on 2026-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_applicationlog_action_alter_job_headless_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('xing', 'Xing'), ('stepstone', 'Stepstone')], max_length=20),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='username',
            field=models.CharField(blank=True, help_text='Login Mail ID / User ID', max_length=255),
        ),
    ]
