# Generated by Django 5.2.10 on 2026-02-06 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_platformconfig_platform_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformconfig',
            options={'verbose_name': 'Platform Configuration', 'verbose_name_plural': 'Platform Configurations'},
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='platformconfig',
            name='daily_apply_limit',
        ),
        migrations.RemoveField(
            model_name='platformconfig',
            name='search_url_template',
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_app_password',
            field=models.CharField(blank=True, help_text='vofyrcqjpfkiemfw', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_for_otp',
            field=models.EmailField(blank=True, help_text='alwinroyadat2003@gmail.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='imap_server',
            field=models.CharField(default='imap.gmail.com', help_text='Server for reading emails (default: imap.gmail.com)', max_length=100),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='action',
            field=models.CharField(choices=[('info', 'System Information'), ('action', 'Browser Action'), ('success', 'Success Achievement'), ('error', 'Critical Error'), ('search', 'Searching'), ('fill', 'Filling Form'), ('submit', 'Submitting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='password',
            field=models.CharField(default='', help_text='Login Password for the platform', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('xing', 'Xing'), ('stepstone', 'Stepstone'), ('indeed', 'Indeed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='username',
            field=models.CharField(help_text='Login Mail ID for the platform (e.g. your LinkedIn Email)', max_length=255),
        ),
    ]
