# Generated by Django 5.2.10 on 2026-02-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_platformconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedjobmatch',
            name='tailored_cv_text',
            field=models.TextField(help_text='ATS-optimized resume content with [SUMMARY], [EXPERIENCE], [PROJECTS], [SKILLS] sections'),
        ),
    ]
