# Generated by Django 5.2.10 on 2026-02-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_automatedjobmatch_tailored_cv_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedjobmatch',
            name='applied_at',
            field=models.DateTimeField(blank=True, help_text='When the application was actually submitted', null=True),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='daily_apply_limit',
            field=models.IntegerField(default=10, help_text='Maximum applications per day'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='search_url_template',
            field=models.CharField(blank=True, help_text='Custom search URL template', max_length=500),
        ),
        migrations.AlterField(
            model_name='automatedjobmatch',
            name='tailored_cv_text',
            field=models.TextField(help_text='ATS-optimized resume content'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='imap_server',
            field=models.CharField(default='imap.gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='username',
            field=models.CharField(help_text='Login Mail ID for the platform', max_length=255),
        ),
    ]
