# Generated by Django 5.2.10 on 2026-02-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_automatedjobmatch_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Berlin, Germany or Munich', max_length=255),
        ),
    ]
