# Generated by Django 5.2.10 on 2026-03-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_job_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automatedjobmatch',
            unique_together={('job_query', 'job_url')},
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='action',
            field=models.CharField(choices=[('info', 'System Information'), ('action', 'Browser Action'), ('success', 'Success Achievement'), ('warning', 'Warning'), ('error', 'Critical Error'), ('search', 'Searching'), ('fill', 'Filling Form'), ('submit', 'Submitting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='automatedjobmatch',
            name='status',
            field=models.CharField(choices=[('found', 'Found'), ('tailoring', 'Tailoring CV'), ('ready', 'Ready to Apply'), ('applying', 'Applying'), ('applied', 'Applied'), ('email_sent', 'Email Notification Sent'), ('failed', 'Failed'), ('duplicate', 'Duplicate Skipped'), ('completed', 'Completed')], default='found', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
