# Generated by Django 5.2 on 2026-01-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. LinkedIn, Indeed, Xing, or Amazon', max_length=255, unique=True)),
                ('platform_type', models.CharField(choices=[('social', 'Social Media (LinkedIn/Xing)'), ('board', 'Job Board (Indeed/Stepstone)'), ('app', 'Job Search App'), ('direct', 'Direct Company Website'), ('agency', 'Recruitment Agency')], default='board', max_length=20)),
                ('website', models.TextField(blank=True, help_text='URL of the platform or company career page', null=True)),
                ('location', models.CharField(blank=True, default='', help_text='Main office or region (e.g. Berlin, Munich, Remote)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Specific search filters or login reminders for this platform', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform / Company',
                'verbose_name_plural': 'Platforms & Companies',
            },
        ),
    ]
