# Generated by Django 5.2.10 on 2026-03-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Main office or region (e.g. Berlin, Munich, Remote)', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Specific search filters or login reminders for this platform'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='URL of the platform or company career page', null=True),
        ),
    ]
